# Generated by Django 3.1.7 on 2021-04-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='plan_type',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.FloatField(choices=[(120, 120), (165, 165), (200, 200)]),
        ),
    ]
