# Generated by Django 3.1.7 on 2021-04-04 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('views', models.IntegerField()),
                ('seasons', models.IntegerField()),
                ('date', models.DateField()),
                ('maturity_rating', models.CharField(max_length=5)),
                ('img', models.URLField()),
                ('video', models.URLField()),
                ('trailer', models.URLField()),
                ('actors', models.ManyToManyField(to='movies.Actors')),
                ('genre', models.ManyToManyField(to='movies.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('duration', models.IntegerField()),
                ('seasons', models.IntegerField()),
                ('episode_number', models.IntegerField()),
                ('img', models.URLField()),
                ('video', models.URLField()),
                ('series_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Series.series')),
            ],
        ),
    ]
