# Generated by Django 3.1.7 on 2021-04-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('release_year', models.DateField()),
                ('maturity_rating', models.CharField(max_length=10)),
                ('duration', models.IntegerField()),
                ('views', models.IntegerField()),
                ('rate', models.FloatField()),
                ('director', models.CharField(max_length=100)),
                ('trailer', models.URLField(max_length=100)),
                ('video', models.URLField(max_length=100)),
                ('poster', models.URLField(max_length=100)),
                ('actors', models.ManyToManyField(to='movies.Actors')),
                ('genres', models.ManyToManyField(to='movies.Genre')),
                ('writers', models.ManyToManyField(to='movies.Writer')),
            ],
        ),
    ]
