# Generated by Django 3.1.7 on 2021-04-10 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='poster',
            new_name='img',
        ),
    ]
